# Copyright (c) 2026 HokyKwan <hokykwan0@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y

CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y
CONFIG_ESP_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y

CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Antidash"
CONFIG_BT_MAX_CONN=1
CONFIG_MAIN_STACK_SIZE=4096
